language: python
python:
    - "2.7"
install:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pip install -e .
script:
    - flake8
    - py.test
notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/7bd6d69bcfa59bddf1e2
        on_start: never
